"""Public entry points for the ActionRail Maya viewport overlay."""

from __future__ import annotations

from .action_book import ActionBookEntry, action_book_entries, action_book_entry_by_id
from .authoring import (
    DraftRail,
    DraftSlot,
    build_draft_spec,
    load_user_preset,
    save_user_preset,
    spec_to_payload,
    user_preset_dir,
    user_preset_ids,
)
from .diagnostics import (
    DiagnosticIssue,
    DiagnosticReport,
    clear_last_report,
    collect_diagnostics,
    diagnose_icon_import,
    diagnose_publish_spec,
    diagnose_spec,
    format_report,
    last_report,
    safe_start,
    show_last_report,
)
from .edit_mode import (
    EditModeSettings,
    EditModeState,
    RailFrameInfo,
    RailSlotInfo,
    edit_mode_state,
    enter_edit_mode,
    exit_edit_mode,
    save_edit_mode_layout,
    select_edit_mode_rail,
    set_edit_mode_options,
    toggle_edit_mode,
)
from .icons import IconDescriptor, list_icon_descriptors
from .maya_ui import (
    diagnose_icon_import_from_maya,
    install_menu_toggle,
    install_preset_shelf_toggle,
    install_shelf_toggle,
    restore_quick_create_panel,
    run_diagnostics_from_maya,
    show_quick_create_panel,
    toggle_default,
    uninstall_menu_toggle,
    uninstall_shelf_toggle,
)
from .preset_store import (
    PresetEntry,
    PresetStore,
    preset_entries,
    preset_ids,
    preset_user_override_id,
    resolve_preset,
)
from .project import about
from .quick_create import (
    QuickCreateSaveResult,
    clear_quick_create_previews,
    load_quick_create_preset,
    preview_quick_create_draft,
    save_quick_create_preset,
)
from .runtime import (
    active_overlay_ids,
    active_overlay_states,
    hide_all,
    lock_rail_slots,
    reload,
    run_action,
    run_slot,
    set_rail_slots_unlocked,
    show_example,
    show_preset,
    show_spec,
    unlock_rail_slots,
    update_slot_key_label,
)
from .spec import (
    RailCollapse,
    RailLayout,
    StackItem,
    StackSpec,
    action_ids,
    builtin_preset_ids,
    load_builtin_preset,
    load_preset,
    parse_stack_spec,
)

__all__ = [
    "DiagnosticIssue",
    "ActionBookEntry",
    "IconDescriptor",
    "PresetEntry",
    "PresetStore",
    "QuickCreateSaveResult",
    "DiagnosticReport",
    "DraftRail",
    "DraftSlot",
    "EditModeSettings",
    "EditModeState",
    "RailCollapse",
    "RailLayout",
    "RailFrameInfo",
    "RailSlotInfo",
    "StackItem",
    "StackSpec",
    "__version__",
    "active_overlay_ids",
    "active_overlay_states",
    "action_book_entries",
    "action_book_entry_by_id",
    "about",
    "action_ids",
    "build_draft_spec",
    "builtin_preset_ids",
    "clear_last_report",
    "collect_diagnostics",
    "clear_quick_create_previews",
    "diagnose_icon_import",
    "diagnose_icon_import_from_maya",
    "diagnose_publish_spec",
    "diagnose_spec",
    "edit_mode_state",
    "enter_edit_mode",
    "exit_edit_mode",
    "format_report",
    "hide_all",
    "install_menu_toggle",
    "install_preset_shelf_toggle",
    "install_shelf_toggle",
    "last_report",
    "list_icon_descriptors",
    "load_builtin_preset",
    "load_preset",
    "load_quick_create_preset",
    "load_user_preset",
    "lock_rail_slots",
    "parse_stack_spec",
    "preset_entries",
    "preset_ids",
    "preset_user_override_id",
    "preview_quick_create_draft",
    "reload",
    "resolve_preset",
    "run_action",
    "run_diagnostics_from_maya",
    "run_slot",
    "safe_start",
    "save_user_preset",
    "set_rail_slots_unlocked",
    "save_edit_mode_layout",
    "save_quick_create_preset",
    "select_edit_mode_rail",
    "set_edit_mode_options",
    "show_example",
    "show_last_report",
    "show_preset",
    "show_quick_create_panel",
    "show_spec",
    "spec_to_payload",
    "toggle_default",
    "toggle_edit_mode",
    "unlock_rail_slots",
    "update_slot_key_label",
    "uninstall_menu_toggle",
    "uninstall_shelf_toggle",
    "user_preset_dir",
    "user_preset_ids",
    "restore_quick_create_panel",
]

__version__ = "0.1.0"
